post_list:
    path: /
    controller: App\Controller\PostController::list
    methods:    GET

post_add:
  path: /add
  controller: App\Controller\PostController::add
  methods:    GET

# api
post_create:
  path: /create
  controller: App\Controller\PostController::create
  methods: POST
